/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.sf.jailer.ui;

import javax.swing.ImageIcon;
import javax.swing.SwingConstants;

/**
 *
 * @author RalfW
 */
public class WelcomePanel extends javax.swing.JPanel {

    /**
     * Creates new form WelcomePanel
     */
    public WelcomePanel() {
        initComponents();
        
        okButton.setIcon(UIUtil.scaleIcon(okButton, okIcon));
        noButton.setIcon(UIUtil.scaleIcon(noButton, cancelIcon));
        notYetButton.setIcon(UIUtil.scaleIcon(notYetButton, closeIcon));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        infoLabel = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        notYetButton = new javax.swing.JButton();
        noButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setLayout(new java.awt.GridBagLayout());

        infoLabel.setText("jLabel1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(33, 0, 8, 0);
        add(infoLabel, gridBagConstraints);

        okButton.setFont(okButton.getFont().deriveFont(okButton.getFont().getSize()+4f));
        okButton.setText("Ok, show the demo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 110, 8, 0);
        add(okButton, gridBagConstraints);

        notYetButton.setFont(notYetButton.getFont().deriveFont(notYetButton.getFont().getSize()+4f));
        notYetButton.setText("Not yet, ask me later");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 110, 8, 0);
        add(notYetButton, gridBagConstraints);

        noButton.setFont(noButton.getFont().deriveFont(noButton.getFont().getSize()+4f));
        noButton.setText("No, let me go on");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 110, 16, 0);
        add(noButton, gridBagConstraints);

        jPanel1.setLayout(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jPanel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel infoLabel;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JButton noButton;
    public javax.swing.JButton notYetButton;
    public javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
    
    private static ImageIcon okIcon;
	private static ImageIcon cancelIcon;
	private static ImageIcon closeIcon;
	
	static {
		// load images
		okIcon = UIUtil.readImage("/buttonok.png");
        cancelIcon = UIUtil.readImage("/buttoncancel.png");
        closeIcon = UIUtil.readImage("/right.png");
	}
}
