SELECT
     T.TABNAME AS TABLENAME, 
     PK.COLNAME,
     PK.TYPENAME,
     CASE WHEN PK.TYPENAME in (''VARCHAR'', ''DECIMAL'') THEN PK.LENGTH ELSE 0 END AS LENGTH,
     PK.KEYSEQ
FROM syscat.TABLES T JOIN syscat.COLUMNS PK ON T.TABNAME=PK.TABNAME AND PK.TABSCHEMA=T.TABSCHEMA
WHERE T.TABSCHEMA=UPPER(''{0}'') AND T.TYPE=''T'' AND PK.KEYSEQ IS NOT NULL AND NOT T.TABNAME IN (''DEPENDENCY'', ''ENTITY'', ''ENTITY_GRAPH'', ''ENTITY_SET_ELEMENT'')

UNION ALL

SELECT
     T.TABNAME AS TABLENAME, 
     C.COLNAME,
     C.TYPENAME,
     CASE WHEN C.TYPENAME in (''VARCHAR'', ''DECIMAL'') THEN C.LENGTH ELSE 0 END AS LENGTH,
     C.COLNO
FROM syscat.TABLES T JOIN syscat.COLUMNS C ON T.TABNAME=C.TABNAME AND C.TABSCHEMA=T.TABSCHEMA
WHERE T.TABSCHEMA=UPPER(''{0}'') AND T.TYPE=''T'' AND NOT T.TABNAME IN (''DEPENDENCY'', ''ENTITY'', ''ENTITY_GRAPH'', ''ENTITY_SET_ELEMENT'') AND NOT EXISTS (SELECT * FROM syscat.COLUMNS PK WHERE PK.TABNAME=T.TABNAME AND PK.TABSCHEMA=T.TABSCHEMA AND PK.KEYSEQ IS NOT NULL)

ORDER BY TABLENAME

