{CALL SYSPROC.ADMIN_CMD ('RUNSTATS ON TABLE ${JAILER_ENTITY} AND DETAILED INDEXES ALL')};
{CALL SYSPROC.ADMIN_CMD ('RUNSTATS ON TABLE ${JAILER_DEPENDENCY} AND DETAILED INDEXES ALL')};
{CALL SYSPROC.ADMIN_CMD ('RUNSTATS ON TABLE ${JAILER_GRAPH} AND DETAILED INDEXES ALL')};
{CALL SYSPROC.ADMIN_CMD ('RUNSTATS ON TABLE ${JAILER_SET} AND DETAILED INDEXES ALL')};
