/*
 * RestrictionEditor.java
 *
 * Created on 14. November 2007, 13:29
 */

package org.jailer.ui;

/**
 *
 * @author  wisser
 */
public class RestrictionEditor extends javax.swing.JPanel {
    
    /** Creates new form RestrictionEditor */
    public RestrictionEditor() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Erzeugter Quelltext ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridBagLayout());

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variablendeklaration - nicht modifizieren//GEN-BEGIN:variables
    // Ende der Variablendeklaration//GEN-END:variables
    
}
